####################################################
# DVrouter.py
# Name:
# HUID:
#####################################################

from router import Router
from packet import Packet
import json


class DVrouter(Router):
    """Distance vector routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        # TODO
        #   add your own class fields and initialization code here
        self.routers = {}
        self.routers[addr] = (0, None)
        self.neighbors = {}
        self.neighbor_routers = {}

    def handle_packet(self, port, packet):
        """Process incoming packet."""
        # TODO
        if packet.is_traceroute:
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)
            dst = packet.dst_addr
            if dst == self.addr:
                return
            
            if dst in self.routers:
                cost, out_port = self.routers[dst]
                if out_port is not None:
                    self.send(out_port, packet)
            
        else:
            # Hint: this is a routing packet generated by your routing protocol
            # If the received distance vector is different
            #   update the local copy of the distance vector
            #   update the distance vector of this router
            #   update the forwarding table
            #   broadcast the distance vector of this router to neighbors
            neighbor = packet.src_addr
            self.neighbor_routers[neighbor] = json.loads(packet.content)

            self.run_bellman_ford()

            

    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors
        self.neighbors[port] = (endpoint, cost)

        self.run_bellman_ford()

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        #   update the distance vector of this router
        #   update the forwarding table
        #   broadcast the distance vector of this router to neighbors
        if port not in self.neighbors:
            return
        
        n_address, _ = self.neighbors[port]
        del self.neighbors[port]

        if n_address in self.neighbor_routers:
            del self.neighbor_routers[n_address]

        self.run_bellman_ford()

    def handle_time(self, time_ms):
        """Handle current time."""
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms
            # TODO
            #   broadcast the distance vector of this router to neighbors
            self.broadcast_distance_vector()

    def broadcast_distance_vector(self):
        my_dv = {dst: cost for dst, (cost, _) in self.routers.items()}
        for out_port in self.neighbors:
            update_packet = Packet(Packet.ROUTING, self.addr, "broadcast", content=json.dumps(my_dv))
            self.send(out_port, update_packet)

    def run_bellman_ford(self):
        new_routers = {self.addr: (0, None)}
        for p, (n_address, link_cost) in self.neighbors.items():
            if n_address not in new_routers or link_cost < new_routers[n_address][0]:
                new_routers[n_address] = (link_cost, p)

            if n_address in self.neighbor_routers:
                for dst, remaining_cost in self.neighbor_routers[n_address].items():
                    total_cost = link_cost + remaining_cost

                    if dst not in new_routers or total_cost < new_routers[dst][0]:
                        new_routers[dst] = (total_cost, p)

        if new_routers != self.routers:
            self.routers = new_routers
            self.broadcast_distance_vector()


    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        debug_str = f"=== Router {self.addr} ===\n"
        debug_str += "Neighbors:\n"
        for port, (n_address, cost) in self.neighbors.items():
            debug_str += f"  Port {port}: {n_address} (Cost: {cost})\n"
            
        debug_str += "\nForwarding Table:\n"
        for dst, (cost, port) in self.routers.items():
            if cost >= 16:
                cost_str = "INFINITY"
            else:
                cost_str = str(cost)
            debug_str += f"  Dest {dst}: Cost = {cost_str}, via Port = {port}\n"
            
        return debug_str
