####################################################
# LSrouter.py
# Name:
# HUID:
#####################################################

from router import Router
from packet import Packet
import heapq 


class LSrouter(Router):
    """Link state routing protocol implementation.

    Add your own class fields and initialization code (e.g. to create forwarding table
    data structures). See the `Router` base class for docstrings of the methods to
    override.
    """

    def __init__(self, addr, heartbeat_time):
        Router.__init__(self, addr, heartbeat_time)  # Initialize base class - DO NOT REMOVE
        self.heartbeat_time = heartbeat_time
        self.last_time = 0
        # TODO
        #   add your own class fields and initialization code here
        #Lưu các link trực tiếp: port -> (endpoint, cost)
        self.neighbors={}   #port -> (neighbor_addr,cost)

        #Topology toàn mạng : src -> {dst -> cost}
        self.topology = {}

        #Save newest sequence number from router source 
        self.lsp_seq = {}

        self.seq = 0   #sequence number hien tai 
        self.forwarding_table = {} #dst => port 


        

    def handle_packet(self, port, packet):
        """Process incoming packet."""
        # TODO
        if packet.is_traceroute: #packet có mục đích chuyển tới đích 
            # Hint: this is a normal data packet
            # If the forwarding table contains packet.dst_addr
            #   send packet based on forwarding table, e.g., self.send(port, packet)

            
            destination = packet.dst_addr #get des

            if destination in self.forwarding_table:#find port tuong ung destination in forwarding table 
                self.send(self.forwarding_table[destination], packet= packet)
            pass
        else:#packet có mục đích giao tiếp các router với nhau . 
            # Hint: this is a routing packet generated by your routing protocol
            # If the sequence number is higher and the received link state is different
            #   update the local copy of the link state
            #   update the forwarding table
            #   broadcast the packet to other neighbors

            #encode packet
            src, seq, links = eval(packet.content) #convert to object
            
            #ignore packet if packet was viewed yet 
            if src in self.lsp_seq and self.lsp_seq[src] >= seq:
                return
            #Save new lsp
            self.lsp_seq[src] = seq
            self.topology[src] = links

            #flood other port (exclude sender router)
            for p in self.links:
                if p!= port:
                    self.send(p,packet=packet)

            self._run_dijkstra()
            pass

    def handle_new_link(self, port, endpoint, cost):
        """Handle new link."""
        # TODO
        #   update local data structures and forwarding table
        #   broadcast the new link state of this router to all neighbors

        self.neighbors[port] = (endpoint,cost)

        #Update topology chính mình => 0 
        if self.addr not in self.topology:
            self.topology[self.addr] = {}
        #Update topology  của enpoint 
        self.topology[self.addr][endpoint] = cost

        #Transform link state info to neighbors : 
        self._flood_lsp()
        self._run_dijkstra()
        

    def handle_remove_link(self, port):
        """Handle removed link."""
        # TODO
        #   update local data structures and forwarding table
        #   broadcast the new link state of this router to all neighbors
        if port in self.neighbors:
            endpoint, _ = self.neighbors.pop(port)
            if self.addr in self.topology:
                self.topology[self.addr].pop(endpoint,None)
        
        self._flood_lsp()
        self._run_dijkstra()
        

    def handle_time(self, time_ms):
        """Handle current time."""
        if time_ms - self.last_time >= self.heartbeat_time:
            self.last_time = time_ms #update last_time 
            self._flood_lsp()
            # TODO
            #   broadcast the link state of this router to all neighbors
            
    
    def _flood_lsp(self):
        self.seq += 1

        self.lsp_seq[self.addr] = self.seq

        #links : (addr , cost) to neighbor of self router 
        links = {ep: cost for (ep,cost) in self.neighbors.values()}
     
        content = str((self.addr,self.seq,links)) #convert to string 

        #Ecapsulate packet typed ROUTING != TRACEROUTER
        packet = Packet(Packet.ROUTING, self.addr, None, content= content)

        #Gửi cho hàng xóm 
        for port in self.links:
            self.send(port, packet)

    def _run_dijkstra(self):
        #init dist : [self.addr] = 0 , [!self.addr]=MAX
        dist ={self.addr: 0}
       
      
        prev_port = {} #node nao => port tương ứng di ra tại self 
        heap = [(0, self.addr, None)] #init PQ min (add self)

        while heap:
            cost, node,first_hop_port = heapq.heappop(heap) # get min cost current and not marked 
            if node in prev_port:
                continue #ignore node marked yet

            prev_port[node] = first_hop_port

            for neighbor, link_cost in self.topology.get(node, {}).items():
                new_cost = cost + link_cost #evaluate new cost 
                if neighbor not in dist or  new_cost < dist[neighbor]:#have been marked before or new_cost < dist[neighbor] (current) 
                    dist[neighbor] = new_cost
                    if node == self.addr:
                        port = self._port_to(neighbor) # find port to go to neighbor of this router  
                    else: 
                        port = first_hop_port # only remember first port where packet needing go through firstly 
                    heapq.heappush(heap, (new_cost, neighbor, port))

        #update forwarding table by prev_port completed 
        self.forwarding_table= {
            node: port
            for node, port in prev_port.items()
            if node != self.addr and port is not None
        }
   


    def _port_to(self, addr):
        for port, (ep, _) in self.neighbors.items():
            if ep == addr:
                return port
        return None

    def __repr__(self):
        """Representation for debugging in the network visualizer."""
        # TODO
        #   NOTE This method is for your own convenience and will not be graded
        return f"LSrouter(addr={self.addr})"
